services:
  cyberchef-api:
    build: ./api
    ports:
    - "8000:8000"

  cyberchef-ui:
    build: ./ui
    ports:
    - "8001:8001"

  cyberchef-ws:
    build: ./ws
    ports:
    - "80:80"

  mariadb:
    image: "mariadb:latest"
